### ISSUE TITLE
Two identical names 

### ISSUE THREAD

**Issue by josephmiller2000** [ThalKod/Chat-App-IO#1]
People can enter with two identical names, 

for example 
user 1 : John
user 2 : John 

they both can enter into the chat with two same names

![snap_2018 05 07_14h51m31s_002_](https://user-images.githubusercontent.com/24210340/39694816-2f3a0c3e-5206-11e8-96bc-342de9258b70.png)

FIX it

**Comment by ThalKod** [comment]
Fixed.
6ba082ac9862a902034186eee498d882ce6609bc

**Comment by josephmiller2000** [comment]
Still, we can use two identical names by adding space in front of the name and at the end of the name.

![snap_2018 05 07_21h12m27s_006_](https://user-images.githubusercontent.com/24210340/39710822-890fbdf0-523b-11e8-831b-26599d0af352.png)

**Comment by ThalKod** [comment]
Check again

**Comment by josephmiller2000** [comment]
Ok here u go :) another method to clone names. + console log produces [] 

![snap_2018 05 07_21h56m34s_009_](https://user-images.githubusercontent.com/24210340/39712716-ad144602-5241-11e8-8c4f-68c68cd32886.png)

**Comment by ThalKod** [comment]
ahaha :) check again

**Comment by josephmiller2000** [comment]
that's fixed now :) cool.
